---
services:
  nginxproxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxproxy
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Sao_Paulo
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "~/nginx/data:/data"
      - "~/nginx/letsencrypt:/etc/letsencrypt"
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Sao_Paulo
    volumes:
      - "~/jellyfin:/config"
      - "~/jellyfin/tvshows:/data/tvshows"
      - "~/jellyfin/movies:/data/movies"
    restart: unless-stopped
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Sao_Paulo
      - DELUGE_LOGLEVEL=error
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - "~/deluge:/config"
      - "~/jellyfin/movies:/movies"
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Sao_Paulo
      - WEBPASSWORD=password
      - PIHOLE_DNS_=1.1.1.1;9.9.9.9
      - DNSSEC=false
      - VIRTUAL_HOST=pihole.phrmendes.duckdns.org
      - WEBTHEME=default-dark
      - PIHOLE_DOMAIN=lan
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - "~/etc-pihole:/etc/pihole"
      - "~/etc-dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
